/**
 * Database schema — plain, idempotent SQLite DDL applied on boot.
 *
 * Runs unchanged on Turso (libsql over HTTPS), on local SQLite files
 * (zero-setup development) and on in-memory SQLite (tests). Identifiers are
 * TEXT UUIDs generated by the application, TEXT columns hold JSON payloads
 * (sources, SEO, key ideas, answers, tags) and timestamps are ISO-8601 UTC
 * strings so lexicographic order equals chronological order.
 */
export const SCHEMA_VERSION = '3.0.0';

/** ISO-8601 UTC "now" usable as a column default on every SQLite build. */
const NOW = `(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const schema: string[] = [
  // ── Identity, roles and permissions ────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    level INTEGER NOT NULL DEFAULT 0,
    is_system INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS permissions (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    grp TEXT NOT NULL DEFAULT 'general',
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS role_permissions (
    role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    avatar_url TEXT,
    headline TEXT NOT NULL DEFAULT '',
    bio TEXT NOT NULL DEFAULT '',
    role_id TEXT NOT NULL REFERENCES roles(id),
    preferences TEXT NOT NULL DEFAULT '{}',
    is_active INTEGER NOT NULL DEFAULT 1,
    email_verified INTEGER NOT NULL DEFAULT 0,
    last_login_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id)`,
  `CREATE INDEX IF NOT EXISTS idx_users_created ON users(created_at)`,
  `CREATE TABLE IF NOT EXISTS password_resets (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS user_devices (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    platform TEXT NOT NULL DEFAULT 'android',
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,

  // ── Taxonomy ───────────────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    section TEXT NOT NULL DEFAULT 'GENERAL',
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    icon TEXT NOT NULL DEFAULT '',
    position INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_categories_section ON categories(section)`,

  // ── Courses / LMS ──────────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS courses (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    summary TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL DEFAULT '',
    section TEXT NOT NULL DEFAULT 'GENERAL',
    category_id TEXT REFERENCES categories(id),
    instructor_id TEXT REFERENCES users(id),
    instructor_name TEXT NOT NULL DEFAULT '',
    difficulty TEXT NOT NULL DEFAULT 'BEGINNER',
    language TEXT NOT NULL DEFAULT 'en',
    duration_minutes INTEGER NOT NULL DEFAULT 0,
    thumbnail_url TEXT,
    tags TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'DRAFT',
    is_featured INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    seo TEXT NOT NULL DEFAULT '{}',
    published_at TEXT,
    scheduled_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_courses_status ON courses(status)`,
  `CREATE INDEX IF NOT EXISTS idx_courses_section ON courses(section)`,
  `CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category_id)`,
  `CREATE INDEX IF NOT EXISTS idx_courses_featured ON courses(is_featured)`,
  `CREATE TABLE IF NOT EXISTS modules (
    id TEXT PRIMARY KEY,
    course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    position INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_modules_course ON modules(course_id)`,
  `CREATE TABLE IF NOT EXISTS lessons (
    id TEXT PRIMARY KEY,
    module_id TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    slug TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT 'TEXT',
    video_url TEXT,
    attachments TEXT NOT NULL DEFAULT '[]',
    notes TEXT NOT NULL DEFAULT '',
    duration_minutes INTEGER NOT NULL DEFAULT 0,
    position INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    is_preview INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_lessons_module ON lessons(module_id)`,
  `CREATE INDEX IF NOT EXISTS idx_lessons_status ON lessons(status)`,
  `CREATE TABLE IF NOT EXISTS enrollments (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    last_lesson_id TEXT,
    last_accessed_at TEXT,
    enrolled_at TEXT NOT NULL DEFAULT ${NOW},
    completed_at TEXT,
    PRIMARY KEY (user_id, course_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_enrollments_course ON enrollments(course_id)`,
  `CREATE TABLE IF NOT EXISTS lesson_progress (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    completed INTEGER NOT NULL DEFAULT 1,
    seconds_spent INTEGER NOT NULL DEFAULT 0,
    completed_at TEXT NOT NULL DEFAULT ${NOW},
    PRIMARY KEY (user_id, lesson_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_progress_lesson ON lesson_progress(lesson_id)`,
  `CREATE TABLE IF NOT EXISTS assignments (
    id TEXT PRIMARY KEY,
    course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    module_id TEXT REFERENCES modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    instructions TEXT NOT NULL DEFAULT '',
    points INTEGER NOT NULL DEFAULT 10,
    due_at TEXT,
    position INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS assignment_submissions (
    id TEXT PRIMARY KEY,
    assignment_id TEXT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL DEFAULT '',
    attachment_url TEXT,
    score INTEGER,
    feedback TEXT NOT NULL DEFAULT '',
    submitted_at TEXT NOT NULL DEFAULT ${NOW},
    graded_at TEXT
  )`,

  // ── Quizzes, MCQs and model tests ──────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS quizzes (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT 'QUIZ',
    course_id TEXT REFERENCES courses(id) ON DELETE CASCADE,
    module_id TEXT REFERENCES modules(id) ON DELETE CASCADE,
    category_id TEXT REFERENCES categories(id),
    duration_minutes INTEGER NOT NULL DEFAULT 0,
    question_count INTEGER NOT NULL DEFAULT 0,
    total_marks REAL NOT NULL DEFAULT 0,
    pass_marks REAL NOT NULL DEFAULT 0,
    negative_mark REAL NOT NULL DEFAULT 0,
    shuffle_questions INTEGER NOT NULL DEFAULT 1,
    show_explanations INTEGER NOT NULL DEFAULT 1,
    max_attempts INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    is_featured INTEGER NOT NULL DEFAULT 0,
    attempts_count INTEGER NOT NULL DEFAULT 0,
    published_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_quizzes_status ON quizzes(status)`,
  `CREATE INDEX IF NOT EXISTS idx_quizzes_kind ON quizzes(kind)`,
  `CREATE TABLE IF NOT EXISTS questions (
    id TEXT PRIMARY KEY,
    quiz_id TEXT REFERENCES quizzes(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'MCQ',
    options TEXT NOT NULL DEFAULT '[]',
    correct TEXT NOT NULL DEFAULT '0',
    explanation TEXT NOT NULL DEFAULT '',
    marks REAL NOT NULL DEFAULT 1,
    difficulty TEXT NOT NULL DEFAULT 'MEDIUM',
    category_id TEXT REFERENCES categories(id),
    source TEXT NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'PUBLISHED',
    position INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_questions_quiz ON questions(quiz_id)`,
  `CREATE INDEX IF NOT EXISTS idx_questions_category ON questions(category_id)`,
  `CREATE INDEX IF NOT EXISTS idx_questions_difficulty ON questions(difficulty)`,
  `CREATE TABLE IF NOT EXISTS quiz_questions (
    quiz_id TEXT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    question_id TEXT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0,
    marks REAL,
    PRIMARY KEY (quiz_id, question_id)
  )`,
  `CREATE TABLE IF NOT EXISTS attempts (
    id TEXT PRIMARY KEY,
    quiz_id TEXT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_ids TEXT NOT NULL DEFAULT '[]',
    answers TEXT NOT NULL DEFAULT '{}',
    review TEXT NOT NULL DEFAULT '[]',
    score REAL NOT NULL DEFAULT 0,
    total REAL NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    unanswered_count INTEGER NOT NULL DEFAULT 0,
    percentage REAL NOT NULL DEFAULT 0,
    passed INTEGER NOT NULL DEFAULT 0,
    seconds_spent INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'IN_PROGRESS',
    started_at TEXT NOT NULL DEFAULT ${NOW},
    expires_at TEXT,
    submitted_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_attempts_user ON attempts(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_attempts_quiz ON attempts(quiz_id)`,

  // ── Editorial content: articles, knowledge, world, humanity, society ───
  `CREATE TABLE IF NOT EXISTS content (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL DEFAULT 'ARTICLE',
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL DEFAULT '',
    cover_url TEXT,
    category_id TEXT REFERENCES categories(id),
    author_id TEXT REFERENCES users(id),
    author_name TEXT NOT NULL DEFAULT '',
    stance TEXT NOT NULL DEFAULT 'ANALYSIS',
    tags TEXT NOT NULL DEFAULT '[]',
    meta TEXT NOT NULL DEFAULT '{}',
    sources TEXT NOT NULL DEFAULT '[]',
    seo TEXT NOT NULL DEFAULT '{}',
    reading_minutes INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    is_featured INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    published_at TEXT,
    scheduled_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_content_type ON content(type)`,
  `CREATE INDEX IF NOT EXISTS idx_content_status ON content(status)`,
  `CREATE INDEX IF NOT EXISTS idx_content_category ON content(category_id)`,
  `CREATE INDEX IF NOT EXISTS idx_content_published ON content(published_at)`,
  `CREATE TABLE IF NOT EXISTS books (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    author_name TEXT NOT NULL DEFAULT '',
    published_year INTEGER,
    pages INTEGER,
    rating REAL NOT NULL DEFAULT 0,
    cover_url TEXT,
    description TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    key_ideas TEXT NOT NULL DEFAULT '[]',
    lessons TEXT NOT NULL DEFAULT '[]',
    context TEXT NOT NULL DEFAULT '',
    applications TEXT NOT NULL DEFAULT '',
    review TEXT NOT NULL DEFAULT '',
    recommendation TEXT NOT NULL DEFAULT '',
    related TEXT NOT NULL DEFAULT '[]',
    category_id TEXT REFERENCES categories(id),
    author_id TEXT REFERENCES users(id),
    tags TEXT NOT NULL DEFAULT '[]',
    sources TEXT NOT NULL DEFAULT '[]',
    seo TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'DRAFT',
    is_featured INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    published_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW},
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_books_status ON books(status)`,
  `CREATE INDEX IF NOT EXISTS idx_books_featured ON books(is_featured)`,

  // ── Engagement ─────────────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS bookmarks (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL,
    item_id TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT ${NOW},
    UNIQUE (user_id, item_type, item_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_bookmarks_user ON bookmarks(user_id)`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    audience TEXT NOT NULL DEFAULT 'USER',
    title TEXT NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL DEFAULT 'SYSTEM',
    link TEXT NOT NULL DEFAULT '',
    read_at TEXT,
    push_sent_at TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at)`,
  `CREATE TABLE IF NOT EXISTS media (
    id TEXT PRIMARY KEY,
    url TEXT NOT NULL,
    storage_key TEXT NOT NULL DEFAULT '',
    original_name TEXT NOT NULL DEFAULT '',
    mime TEXT NOT NULL DEFAULT '',
    bytes INTEGER NOT NULL DEFAULT 0,
    alt TEXT NOT NULL DEFAULT '',
    folder TEXT NOT NULL DEFAULT 'general',
    uploaded_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_media_created ON media(created_at)`,
  `CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL DEFAULT '{}',
    is_public INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS analytics_events (
    id TEXT PRIMARY KEY,
    event TEXT NOT NULL,
    path TEXT NOT NULL DEFAULT '',
    label TEXT NOT NULL DEFAULT '',
    user_id TEXT,
    referrer TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_event ON analytics_events(event)`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_created ON analytics_events(created_at)`,
  `CREATE TABLE IF NOT EXISTS contacts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'NEW',
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS subscribers (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'SUBSCRIBED',
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE TABLE IF NOT EXISTS activity_log (
    id TEXT PRIMARY KEY,
    actor_id TEXT,
    actor_name TEXT NOT NULL DEFAULT 'system',
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL DEFAULT '',
    entity_id TEXT NOT NULL DEFAULT '',
    entity_label TEXT NOT NULL DEFAULT '',
    meta TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log(created_at)`,
  `CREATE TABLE IF NOT EXISTS recently_viewed (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL,
    item_id TEXT NOT NULL,
    item_title TEXT NOT NULL DEFAULT '',
    item_slug TEXT NOT NULL DEFAULT '',
    viewed_at TEXT NOT NULL DEFAULT ${NOW},
    PRIMARY KEY (user_id, item_type, item_id)
  )`,

  // ── Hacker admin: hourly rotating passcode state ───────────────────────
  `CREATE TABLE IF NOT EXISTS hacker_admin_state (
    id TEXT PRIMARY KEY DEFAULT 'state',
    passcode_hash TEXT NOT NULL,
    issued_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    rotations INTEGER NOT NULL DEFAULT 0,
    last_mail_status TEXT NOT NULL DEFAULT 'PENDING'
  )`,

  // ── Traffic / visitor monitoring (read by the /hackeradmin panel) ──────
  `CREATE TABLE IF NOT EXISTS request_log (
    id TEXT PRIMARY KEY,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    ip TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    referrer TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER NOT NULL DEFAULT 0,
    is_api INTEGER NOT NULL DEFAULT 0,
    user_id TEXT,
    created_at TEXT NOT NULL DEFAULT ${NOW}
  )`,
  `CREATE INDEX IF NOT EXISTS idx_request_log_created ON request_log(created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_request_log_path ON request_log(path)`,
];
